### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by edysegura** [lucianoctrl8/trabalho-dm107#2]
It is not possible to sign up to application even if all fields are filled.

![image](https://cloud.githubusercontent.com/assets/5324414/10884147/8fa4a2cc-815d-11e5-9a26-d1292786fb9b.png)

**Comment by edysegura** [comment]
I was able to include a new user removing the slash "-" from CEP number.

**Comment by lucianoctrl8** [comment]
Yes, to insert a new user you cannot include '-' because de field only allow numbers.

**Comment by edysegura** [comment]
So I'd like to recommend you to improve the user feedback message.
