### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by edysegura** [lucianoctrl8/trabalho-dm107#4]
The swagger documentation is outdated and do not reflect the API implementation.

![image](https://cloud.githubusercontent.com/assets/5324414/10895568/24d91bc8-819c-11e5-8f24-c5f1e2941382.png)
![image](https://cloud.githubusercontent.com/assets/5324414/10895587/37075f4e-819c-11e5-95b1-6ccb7fa6f72c.png)

**Comment by edysegura** [comment]
The same in POST operation.

![image](https://cloud.githubusercontent.com/assets/5324414/10895704/b551cb5a-819c-11e5-91c0-1dd13a227b84.png)

**Comment by edysegura** [comment]
No description for GET by Id operation:

![image](https://cloud.githubusercontent.com/assets/5324414/10895797/3b777d7e-819d-11e5-8bdc-65bccfef00cc.png)

**Comment by lucianoctrl8** [comment]
When you select a delivery that exists, it returns the correct schema. But i saw that when you try to look for a delivery that doesnt exist, an error 404 isnt showing up to the user.
See the image below when you search for an existing delivery:

![screen shot 2015-11-02 at 21 24 35](https://cloud.githubusercontent.com/assets/10127823/10897422/5f4e11e4-81a8-11e5-87e6-750aada495ca.png)

**Comment by lucianoctrl8** [comment]
And yes, it was my bad that the status code is outdated. Thanks.
